/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-dell-ftos-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.force10.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-dell-ftos-id.yang */
public class Force10Id extends ConfNamespace {
    public static final int hash = 1106359230;
    public int hash() {
        return Force10Id.hash;
    }

    public static final String id = "http://tail-f.com/ned/dell-ftos-id";
    public String id() {
        return Force10Id.id;
    }

    public static final String uri = "http://tail-f.com/ned/dell-ftos-id";
    public String uri() {
        return Force10Id.uri;
    }

    public static final String prefix = "force10-id";
    public String prefix() {
        return Force10Id.prefix;
    }

    public Force10Id() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _dell_ftos = 677897875;
    public static final String _dell_ftos_ = "dell-ftos";
}
