/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-a10-acos-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.a10.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-a10-acos-id.yang */
public class tailfNedA10AcosId extends ConfNamespace {
    public static final int hash = 2106339590;
    public int hash() {
        return tailfNedA10AcosId.hash;
    }

    public static final String id = "http://tail-f.com/ned/a10-acos-id";
    public String id() {
        return tailfNedA10AcosId.id;
    }

    public static final String uri = "http://tail-f.com/ned/a10-acos-id";
    public String uri() {
        return tailfNedA10AcosId.uri;
    }

    public static final String prefix = "a10-acos-id";
    public String prefix() {
        return tailfNedA10AcosId.prefix;
    }

    public tailfNedA10AcosId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _a10_acos = 1766880991;
    public static final String _a10_acos_ = "a10-acos";
}
