/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-nx-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.nexus.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-nx-id.yang */
public class CiscoNexusId extends ConfNamespace {
    public static final int hash = 1850480213;
    public int hash() {
        return CiscoNexusId.hash;
    }

    public static final String id = "http://tail-f.com/ned/cisco-nx-id";
    public String id() {
        return CiscoNexusId.id;
    }

    public static final String uri = "http://tail-f.com/ned/cisco-nx-id";
    public String uri() {
        return CiscoNexusId.uri;
    }

    public static final String prefix = "cisco-nx-id";
    public String prefix() {
        return CiscoNexusId.prefix;
    }

    public CiscoNexusId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nx = 1488855246;
    public static final String _cisco_nx_ = "cisco-nx";
}
